[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"

# Redirect index to index.html for single-page routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
